In [1]:
import sys
sys.path.append('../')
from ac_dll_grammar_vae.data import CFGEquationDataset
from ac_dll_grammar_vae.data.transforms import MathTokenEmbedding,RuleTokenEmbedding
from ac_dll_grammar_vae.data.alphabet import alphabet as math_alphabet

In [2]:
data = CFGEquationDataset()

In [3]:
data[42]

['cos', '(', '(', '1', ')', ')', '+', '2']

In [4]:
emb = MathTokenEmbedding(alphabet=math_alphabet)
emb.token_to_idx

{'sqrt': 1,
 '3': 2,
 ')': 3,
 'sin': 4,
 '/': 5,
 '+': 6,
 'x': 7,
 '*': 8,
 'log': 9,
 '(': 10,
 '-': 11,
 'exp': 12,
 '2': 13,
 '1': 14,
 'cos': 15,
 ' ': 0}

In [5]:
cfg = data.get_grammar()
emb = RuleTokenEmbedding(cfg=cfg,one_hot_encode=True)
key = "S -> S '+' T"
emb.rule_to_idx

{"S -> S '+' T": 0,
 "S -> S '*' T": 1,
 "S -> S '/' T": 2,
 "S -> S '-' T": 3,
 'S -> T': 4,
 "T -> '(' S ')'": 5,
 "T -> 'sin' '(' S ')'": 6,
 "T -> 'exp' '(' S ')'": 7,
 "T -> 'cos' '(' S ')'": 8,
 "T -> 'sqrt' '(' S ')'": 9,
 "T -> 'log' '(' S ')'": 10,
 "T -> 'x'": 11,
 "T -> '1'": 12,
 "T -> '2'": 13,
 "T -> '3'": 14,
 "Nothing -> 'None'": 15}

In [6]:
#Example Encoding: 
data_2 = ['sin', '(', '(', '1', ')', ')', '+', 'x']
encoded_data_2 = emb.embed(data_2)
encoded_data_2

[array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]),
 array([0., 0., 0., 0., 0., 0., 0., 0.

In [8]:
x_true_2 = torch.Tensor(encoded_data_2)
x_true_2.shape

most_likely = torch.argmax(x_true_2,dim=-1)
most_likely.reshape(-1)
most_likely

NameError: name 'torch' is not defined

In [9]:
ind_of_ind = torch.Tensor([0,0 ,0 ,0 ,0 ,1 ,1 ,1 ,1 ,1 ,1 ,1 ,1 ,1 ,1 ,2])
masks = torch.Tensor([[1., 1. ,1. ,1., 1. ,0., 0., 0., 0., 0., 0. ,0., 0., 0., 0., 0.],
 [0., 0., 0., 0. ,0. ,1., 1., 1. ,1., 1., 1. ,1. ,1. ,1. ,1., 0.],
 [0., 0., 0., 0. ,0. ,0., 0.,0., 0., 0., 0. ,0., 0., 0., 0., 1.]])

NameError: name 'torch' is not defined

In [75]:
x_true_batch = batch
most_likely_batch  = torch.argmax(x_true_batch,-1)
most_likely_batch = most_likely_batch.reshape(-1)
print(most_likely_batch)
print(ind_of_ind)
ix2 = torch.index_select(ind_of_ind, 0, most_likely_batch).unsqueeze(1)
ix2 = ix2.long()
print(ix2.T)
M2 = masks[ix2]
print(M2.shape)
MAX_LEN = 16
DIM = 16
M3 = M2.view(-1, MAX_LEN, DIM)
print(M3.shape)
print(M3)

tensor([ 0,  4,  8,  4,  5,  4, 12, 13, 15, 15, 15, 15, 15, 15, 15, 15,  0,  4,
         6,  4,  5,  4, 12, 11, 15, 15, 15, 15, 15, 15, 15, 15])
tensor([0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2.])
tensor([[0, 0, 1, 0, 1, 0, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 1, 0, 1, 0, 1, 1,
         2, 2, 2, 2, 2, 2, 2, 2]])
torch.Size([32, 1, 16])
torch.Size([2, 16, 16])
tensor([[[1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
         [1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
         [1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
         [0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
         [0., 0., 

In [ ]:
  # select indices and add dimension
    ix2 = ix2.long()  # cast indices as long ints (equivalent to tf.int32)
    M2 = masks[ix2]  # get slices of masks with indices
    M3 = M2.view(-1, MAX_LEN, DIM)  # reshape them
    P2 = torch.exp(x_pred) * M3  # apply them to the exp-predictions
    P2 = P2 / P2.sum(dim=-1, keepdim=True)  # normalize predictions
    return P2

In [10]:
decoded_data = emb.decode(encoded_data_2)

NameError: name 'encoded_data' is not defined

In [21]:
decoded_data

["cos'", "'('", "('", '1', "')", "')", "'+'", '2']

In [26]:
from ac_dll_grammar_vae import print_contact_info
from ac_dll_grammar_vae.data import CFGEquationDataset
from ac_dll_grammar_vae.data.alphabet import alphabet
from ac_dll_grammar_vae.data.transforms import MathTokenEmbedding, RuleTokenEmbedding, ToTensor, Compose#, PadSequencesToSameLength
import torch.nn.functional as F
import torch
torch.manual_seed(42)
import torch.nn as nn
from torch.utils.data import DataLoader, TensorDataset, Dataset

In [27]:
training_gvae = CFGEquationDataset(
        n_samples=100000,
        transform=Compose([
            RuleTokenEmbedding(cfg,max_num_rules=16),
            ToTensor(dtype=torch.uint8)
        ]))

#Batch Size:
batch_size = 100
MAX_PROD_LEN = 16
training_gvae_loader = DataLoader(dataset=training_gvae,
                              batch_size=batch_size,
                              shuffle=True)

In [28]:
iter_ = iter(training_gvae_loader)
batch = next(iter_)

In [31]:
batch[2]

tensor([ 4,  7,  3,  0,  4, 14, 14,  7,  2,  4,  8,  4, 13, 12, 15, 15],
       dtype=torch.uint8)